# Generated by Django 5.1.1 on 2024-09-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pointsdetails",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_reported",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_post_date",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="like_count_today",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="post_count_today",
        ),
        migrations.DeleteModel(
            name="PointLog",
        ),
        migrations.DeleteModel(
            name="PointsDetails",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
