# Generated by Django 5.1 on 2024-08-29 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Men"), ("N", "None_gender")],
                        default="",
                        max_length=2,
                    ),
                ),
                ("birthday", models.DateField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("TP", "台北市"),
                            ("NTPC", "新北市"),
                            ("TPE", "台中市"),
                            ("TN", "台南市"),
                            ("KH", "高雄市"),
                            ("KHH", "基隆市"),
                            ("TYC", "桃園市"),
                            ("HCC", "新竹市"),
                            ("HSC", "新竹縣"),
                            ("MIA", "苗栗縣"),
                            ("CHW", "彰化縣"),
                            ("NTO", "南投縣"),
                            ("YUN", "雲林縣"),
                            ("CYI", "嘉義市"),
                            ("CYC", "嘉義縣"),
                            ("TNN", "台南縣"),
                            ("KHH", "高雄縣"),
                            ("PIF", "屏東縣"),
                            ("ILA", "宜蘭縣"),
                            ("HUN", "花蓮縣"),
                            ("TTT", "台東縣"),
                            ("PEN", "澎湖縣"),
                            ("KMN", "金門縣"),
                            ("MZC", "馬祖縣"),
                        ],
                        default="TP",
                        max_length=100,
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("MS", "中學以下"),
                            ("HS", "高中、高職"),
                            ("JC", "專科"),
                            ("U", "大學"),
                            ("PG", "研究所以上"),
                        ],
                        default="MS",
                        max_length=200,
                    ),
                ),
                (
                    "investment_experience",
                    models.CharField(
                        choices=[
                            ("0-1", "0-1年"),
                            ("1-3", "1-3年"),
                            ("3-5", "3-5年"),
                            ("5-10", "5年-10年"),
                            ("10-20", "10年-20年"),
                            ("20-30", "20年-30年"),
                            ("30-50", "30年-50年"),
                        ],
                        default="0-1",
                        max_length=20,
                    ),
                ),
                ("investment_tool", models.JSONField(default=list)),
                (
                    "investment_attributes",
                    models.CharField(
                        choices=[
                            ("P", "積極(短線交易)"),
                            ("S", "穩健(波段操作)"),
                            ("C", "保守(長期持有)"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "tot_point",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=None,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
