# Generated by Django 5.1 on 2024-08-28 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Men'), ('N', 'None_gender')], default='', max_length=2)),
                ('birthday', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('Investment_experience', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Investment_tool', models.CharField(max_length=500)),
                ('investment_attributes', models.CharField(choices=[('P', '積極(短線交易)'), ('S', '穩健(波段操作)'), ('C', '保守(長期持有)')], default='', max_length=50)),
                ('tot_point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted_at', models.DateTimeField(verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
