# Generated by Django 5.1.1 on 2024-09-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_deleted_user_deleted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
