# Generated by Django 5.1 on 2024-08-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_deleted_at_remove_profile_tot_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='tot_point',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
