# Generated by Django 5.1 on 2024-08-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_deleted_at_alter_profile_tot_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tot_point',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=10, null=True),
        ),
    ]
