# Generated by Django 5.1 on 2024-08-30 07:55

import django.db.models.deletion
import django.utils.timezone
import lib.models.soft_delete
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stockID', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('post_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['deleted_at'], name='articles_ar_deleted_c8c4cd_idx')],
            },
            bases=(lib.models.soft_delete.SoftDeleteable, models.Model),
        ),
    ]
