# Generated by Django 5.1 on 2024-09-10 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_comment_article"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="collectors",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="collectors",
            field=models.ManyToManyField(
                blank=True,
                related_name="comment_collectors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
