# Generated by Django 5.1.1 on 2024-09-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_article_collectors"),
        ("articles", "0006_industrytag_article_tags_article_stock"),
    ]

    operations = []
