# Generated by Django 5.1.1 on 2024-09-14 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_merge_20240912_1628"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="collectors",
        ),
    ]
