# Generated by Django 5.1.1 on 2024-09-17 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_article_collectors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="collectors",
            field=models.ManyToManyField(
                related_name="collectors", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
