# Generated by Django 5.1.1 on 2024-09-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_profile_points_profile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
