# Generated by Django 5.1.1 on 2024-09-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_delete_profile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_deleted_c8c4cd_idx',
        ),
    ]
