# Generated by Django 5.1.1 on 2024-09-20 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0015_remove_article_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="collectors",
            field=models.ManyToManyField(
                related_name="collected", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
