# Generated by Django 5.1 on 2024-09-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0002_alter_profile_tot_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.CharField(
                choices=[
                    ("middle_school", "中學以下"),
                    ("high_school", "高中、高職"),
                    ("junior_college", "專科"),
                    ("university", "大學"),
                    ("post_graduate", "研究所以上"),
                ],
                default="middle_school",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Female", "女"), ("Men", "男")], default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="investment_attributes",
            field=models.CharField(
                choices=[
                    ("proactive", "積極(短線交易)"),
                    ("stable", "穩健(波段操作)"),
                    ("conservative", "保守(長期持有)"),
                ],
                default="",
                max_length=200,
            ),
        ),
    ]
