# Generated by Django 5.1.1 on 2024-09-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0004_alter_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
