# Generated by Django 5.1.1 on 2024-09-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0010_rename_last_login_date_profile_last_point_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
