# Generated by Django 5.1.1 on 2024-09-26 21:23

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0011_profile_user_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_img",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="user_images/",
            ),
        ),
    ]
