# Generated by Django 5.1 on 2024-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
