# Generated by Django 5.1 on 2024-08-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_userprofile_last_post_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='like_count_today',
            field=models.IntegerField(default=0),
        ),
    ]
