# Generated by Django 5.1 on 2024-08-31 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_userprofile_is_reported_userprofile_like_count_today'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='like_count_today',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='post_count_today',
            new_name='post_count',
        ),
    ]
