# Generated by Django 5.1 on 2024-08-31 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_rename_like_count_today_userprofile_like_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='like_count',
            new_name='like_count_today',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='post_count',
            new_name='post_count_today',
        ),
    ]
